import type { ArticleSummary } from "./articles";

const now = new Date();
function hoursAgo(h: number) {
  return new Date(now.getTime() - h * 3600_000).toISOString();
}

// Used only when Supabase is unconfigured, so the shell renders during setup.
export const PLACEHOLDER_ARTICLES: ArticleSummary[] = [
  {
    id: "p1",
    slug: "openai-launches-new-agentic-platform",
    title: "OpenAI Unveils Agentic Platform, Reshaping the AI Developer Stack",
    dek: "The company's new agent runtime promises persistent memory, tool use, and a marketplace — putting it on a collision course with Anthropic and Google.",
    excerpt:
      "OpenAI's new platform formalizes agents as first-class citizens of its API, a move analysts see as a direct response to the rise of Claude Code and Gemini.",
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "technology",
    subcategory_slug: "artificial-intelligence",
    author_name: "Mira Chen",
    is_breaking: true,
    is_featured: true,
    published_at: hoursAgo(1),
    read_minutes: 6,
  },
  {
    id: "p2",
    slug: "chip-export-rules-tighten",
    title: "U.S. Tightens Chip Export Rules, Citing National Security",
    dek: "New restrictions target advanced GPUs and EDA software, with European allies asked to follow.",
    excerpt:
      "The Commerce Department issued an expanded export control list Friday morning.",
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "politics",
    subcategory_slug: "national-security",
    author_name: "Jordan Park",
    is_breaking: false,
    is_featured: true,
    published_at: hoursAgo(3),
    read_minutes: 5,
  },
  {
    id: "p3",
    slug: "spacex-starship-orbital-flight",
    title: "Starship Completes First Fully Orbital Payload Mission",
    dek: "The milestone clears the way for NASA's lunar return campaign.",
    excerpt: null,
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "science",
    subcategory_slug: "space",
    author_name: "Anya Patel",
    is_breaking: false,
    is_featured: true,
    published_at: hoursAgo(5),
    read_minutes: 4,
  },
  {
    id: "p4",
    slug: "fed-holds-rates-tech-rally",
    title: "Fed Holds Rates Steady; Tech Stocks Lead a Late-Day Rally",
    dek: null,
    excerpt: null,
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "business",
    subcategory_slug: "markets",
    author_name: "Sam Reyes",
    is_breaking: false,
    is_featured: false,
    published_at: hoursAgo(7),
    read_minutes: 3,
  },
  {
    id: "p5",
    slug: "ransomware-hits-european-grid-operator",
    title: "Ransomware Attack Disrupts European Grid Operator",
    dek: null,
    excerpt: null,
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "technology",
    subcategory_slug: "cybersecurity",
    author_name: "Lucas Brandt",
    is_breaking: false,
    is_featured: false,
    published_at: hoursAgo(9),
    read_minutes: 4,
  },
  {
    id: "p6",
    slug: "eu-passes-platform-accountability-act",
    title: "E.U. Passes Sweeping Platform Accountability Act",
    dek: null,
    excerpt: null,
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "world",
    subcategory_slug: "europe",
    author_name: "Hanna Mueller",
    is_breaking: false,
    is_featured: false,
    published_at: hoursAgo(11),
    read_minutes: 5,
  },
  {
    id: "p7",
    slug: "indie-studio-game-of-the-year",
    title: "A Two-Person Studio Just Won Game of the Year",
    dek: null,
    excerpt: null,
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "culture",
    subcategory_slug: "gaming",
    author_name: "Devin Okafor",
    is_breaking: false,
    is_featured: false,
    published_at: hoursAgo(13),
    read_minutes: 3,
  },
  {
    id: "p8",
    slug: "ai-coding-tools-developer-survey",
    title: "AI Coding Tools Now Used Daily by Two-Thirds of Developers",
    dek: null,
    excerpt: null,
    cover_image_url: null,
    cover_image_alt: null,
    category_slug: "technology",
    subcategory_slug: "software",
    author_name: "Priya Shah",
    is_breaking: false,
    is_featured: false,
    published_at: hoursAgo(16),
    read_minutes: 4,
  },
];
